2021-02-03 15:45:24,686 ERROR: Exception on /login [GET] [in /home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/tund/HDD/myblog/app/routes.py", line 71, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/media/tund/HDD/myblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/media/tund/HDD/myblog/app/templates/base.html", line 80, in top-level template code
    {% for message in messages %}
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/media/tund/HDD/myblog/app/templates/base.html", line 52, in block "content"
    {% block app_content %}{% endblock %}
  File "/media/tund/HDD/myblog/app/templates/login.html", line 7, in block "app_content"
    {{ wtf.quick_form(form) }}
  File "/home/tund/anaconda3/envs/flmyblog/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
